<a href="https://www.kaggle.com/code/sagorkumarmitra/tensorflow-keras-walkthrough?scriptVersionId=145490445" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Import Library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: l

In [2]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])
dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [3]:
for elem in dataset:
  print(elem.numpy())

8
3
0
8
2
1


In [4]:
it=iter(dataset)

print(next(it).numpy())

8


In [5]:
print(dataset.reduce(0, lambda state, value: state + value).numpy())

22


In [6]:
print(dataset.reduce(0, lambda state, value: state + value).numpy())

22


In [7]:
tf.random.uniform([4, 10])

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0.9716853 , 0.25670755, 0.66297996, 0.281376  , 0.9447311 ,
        0.42266786, 0.44796562, 0.8277887 , 0.02066684, 0.50636697],
       [0.09913635, 0.39375055, 0.3058827 , 0.22642195, 0.93985987,
        0.25517857, 0.1557672 , 0.40623724, 0.82035327, 0.5808766 ],
       [0.6701946 , 0.7210275 , 0.18298817, 0.80529416, 0.650398  ,
        0.80182886, 0.382501  , 0.07431829, 0.551384  , 0.44440496],
       [0.5383986 , 0.37330258, 0.915481  , 0.22151077, 0.93244195,
        0.3163501 , 0.52111065, 0.55570984, 0.99013436, 0.85404813]],
      dtype=float32)>

In [8]:
import tensorflow as tf
inputs=tf.random.normal(shape=(32, 10))

In [9]:
outputs = tf.keras.activations.softmax(inputs)
tf.reduce_sum(outputs[0, :])

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [10]:
import tensorflow as tf
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [11]:
tf.constant(4)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [12]:
# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [13]:
import numpy as np
np.random.randint(0, 256, size=(64, 200, 200, 3)).astype("float32")

array([[[[150.,  43., 220.],
         [185.,  24.,  49.],
         [223.,   1., 194.],
         ...,
         [ 83., 170.,  81.],
         [ 92., 143., 188.],
         [254., 180.,  40.]],

        [[206., 226., 135.],
         [230., 213., 141.],
         [241.,  47., 235.],
         ...,
         [132.,  99., 151.],
         [  3.,  29., 219.],
         [ 36.,  13.,  97.]],

        [[103., 136., 239.],
         [149., 151.,   2.],
         [211.,  73.,  43.],
         ...,
         [126., 255.,  26.],
         [ 15.,  93.,  75.],
         [ 88.,  67., 106.]],

        ...,

        [[ 94., 202., 178.],
         [ 79.,  67., 187.],
         [239.,   7., 254.],
         ...,
         [115., 105., 241.],
         [195., 255.,   9.],
         [194., 211.,  12.]],

        [[164., 187.,  84.],
         [  8.,  72., 129.],
         [121., 117., 148.],
         ...,
         [210.,  44.,  45.],
         [213., 161.,  40.],
         [ 15., 190.,  12.]],

        [[ 47.,  90., 211.],
       

In [14]:
from tensorflow.keras.layers import Normalization

# Example image data, with values in the [0, 255] range
training_data = np.random.randint(0, 256, size=(64, 200, 200, 3)).astype("float32")

normalizer = Normalization(axis=-1)
normalizer.adapt(training_data)

normalized_data = normalizer(training_data)
print("var: %.4f" % np.var(normalized_data))
print("mean: %.4f" % np.mean(normalized_data))

var: 1.0006
mean: 0.0000


In [15]:
normalized_data

<tf.Tensor: shape=(64, 200, 200, 3), dtype=float32, numpy=
array([[[[-0.738445  , -1.0896399 ,  0.5339331 ],
         [ 0.4530597 ,  1.3064209 ,  1.0889717 ],
         [-0.0208342 , -1.5499002 , -1.6591462 ],
         ...,
         [ 0.8592545 ,  0.07454785, -0.26478097],
         [-1.7133124 ,  0.71079   , -1.2259454 ],
         [-0.7790644 ,  0.6837159 ,  0.8452962 ]],

        [[-0.0749935 , -0.08789695, -1.2800955 ],
         [-0.9009229 , -0.7241391 ,  1.6846229 ],
         [-0.03437402, -0.85950977, -1.4425458 ],
         ...,
         [-0.23747142,  1.3470322 , -0.04818055],
         [ 1.0217324 ,  1.1575131 ,  1.1295843 ],
         [ 0.4936792 ,  0.913846  ,  0.38502032]],

        [[ 0.1822632 ,  1.0221425 , -1.0499575 ],
         [-1.5643743 ,  1.523014  ,  1.6169353 ],
         [-0.35932985, -0.30449003,  0.08719472],
         ...,
         [ 1.4008476 , -1.3333071 , -1.577921  ],
         [ 1.441467  ,  1.6042364 ,  0.5880832 ],
         [ 0.818635  ,  1.712533  ,  1.386797